#!/usr/bin/env node
// Renders fleet.yml into compose services, Prometheus targets and reserve rules.
// Run via `make generate`. Generated files are overwritten wholesale.

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { dirname, join } from 'node:path'
import yaml from 'js-yaml'
import { ROOT, MAX_ALLOWED_DOUBLING, KNOWN_ROLES, loadFleet } from './fleet.mjs'

// bee-factory publishes 1633 + 2n for n in 0..4. Overlapping with it is a
// footgun rather than a mere inconvenience — see fleet.mjs.
const FACTORY_PORTS = new Set([1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642])

// Chromium's kRestrictedPorts (net/base/port_util.cc). Browsers refuse to
// connect to these with ERR_UNSAFE_PORT. Only a warning: nothing in this repo
// browses to the bee API — Prometheus scrapes over the docker network and the
// tools use fetch/curl — but it makes ad-hoc debugging in a browser impossible,
// which is a nasty surprise to hit later. 1719/1720/1723 are the nearest to our
// default base of 1733.
const BROWSER_RESTRICTED_PORTS = new Set([
  0, 1, 7, 9, 11, 13, 15, 17, 19, 20, 21, 22, 23, 25, 37, 42, 43, 53, 69, 77, 79, 87, 95, 101, 102,
  103, 104, 109, 110, 111, 113, 115, 117, 119, 123, 135, 137, 139, 143, 161, 179, 389, 427, 465,
  512, 513, 514, 515, 526, 530, 531, 532, 540, 548, 554, 556, 563, 587, 601, 636, 989, 990, 993,
  995, 1719, 1720, 1723, 2049, 3659, 4045, 5060, 5061, 6000, 6566, 6665, 6666, 6667, 6668, 6669,
  6697, 10080,
])

// Linux's default ephemeral range. A listener inside it can lose the race to an
// outbound connection that grabbed the same port first, which shows up as an
// intermittent bind failure on restart rather than a clean error.
const EPHEMERAL_START = 32768

const BANNER = '# GENERATED by tools/generate.mjs from fleet.yml — do not edit.\n'

const fleet = loadFleet()
const nodes = fleet.nodes
const errors = []
const warnings = []

// ---- validation -------------------------------------------------------------

const seenNames = new Set()
const seenPorts = new Map()

for (const node of nodes) {
  if (!node.name) errors.push('a node is missing "name"')
  if (seenNames.has(node.name)) errors.push(`duplicate node name: ${node.name}`)
  seenNames.add(node.name)

  if (!KNOWN_ROLES.has(node.role)) {
    errors.push(`${node.name}: unknown role "${node.role}" (known: ${[...KNOWN_ROLES].join(', ')})`)
  }
  if (node.doubling < 0 || node.doubling > MAX_ALLOWED_DOUBLING) {
    errors.push(`${node.name}: reserve_capacity_doubling ${node.doubling} outside 0..${MAX_ALLOWED_DOUBLING}`)
  }
  if (!node.isFull && node.doubling !== 0) {
    // bee refuses to start in this combination (node.go:302).
    errors.push(`${node.name}: reserve_capacity_doubling must be 0 for non-full role "${node.role}"`)
  }
  if (node.target_neighborhood && !/^[01]+$/.test(String(node.target_neighborhood))) {
    errors.push(`${node.name}: target_neighborhood "${node.target_neighborhood}" must be binary digits only`)
  }
  if (node.isFull && !node.target_neighborhood) {
    errors.push(
      `${node.name}: full nodes must pin target_neighborhood — ` +
        `an empty value makes bee mine into a suggester-chosen sparse neighborhood (PLAN.md §1)`,
    )
  }
  for (const [label, port] of [['api', node.apiPort], ['p2p', node.p2pPort]]) {
    if (seenPorts.has(port)) errors.push(`port ${port} used by both ${seenPorts.get(port)} and ${node.name}/${label}`)
    seenPorts.set(port, `${node.name}/${label}`)
    if (FACTORY_PORTS.has(port)) {
      errors.push(
        `${node.name}/${label} port ${port} collides with bee-factory's range (1633-1642). ` +
          `Read-only tools would silently query a factory node instead of ours — ` +
          `make addresses could report the wrong wallet to fund. Raise port_base in fleet.yml.`,
      )
    }
    if (BROWSER_RESTRICTED_PORTS.has(port)) {
      warnings.push(
        `${node.name}/${label} port ${port} is on Chromium's restricted-port list; ` +
          `browsers refuse it with ERR_UNSAFE_PORT. Scraping and the CLI tools are unaffected, ` +
          `but you will not be able to open this API in a browser.`,
      )
    }
    if (port >= EPHEMERAL_START) {
      warnings.push(
        `${node.name}/${label} port ${port} is inside Linux's default ephemeral range ` +
          `(${EPHEMERAL_START}+); binds can fail intermittently after a restart. ` +
          `Prefer a port_base below ${EPHEMERAL_START}.`,
      )
    }
  }
}

// Shallow-receipt tolerance is derived from doubling, so full nodes with mixed
// values are not comparable on the receipt metrics we care about.
const fullDoublings = new Set(nodes.filter((n) => n.isFull).map((n) => n.doubling))
if (fullDoublings.size > 1) {
  errors.push(
    `full nodes have mixed reserve_capacity_doubling (${[...fullDoublings].join(', ')}); ` +
      `this changes shallowReceiptTolerance per node and makes receipt metrics incomparable`,
  )
}

if (errors.length) {
  console.error('fleet.yml is invalid:')
  for (const e of errors) console.error(`  - ${e}`)
  process.exit(1)
}

if (warnings.length) {
  console.warn('warnings:')
  for (const w of warnings) console.warn(`  ! ${w}`)
  console.warn('')
}

const enabled = fleet.enabled
if (enabled.length === 0) console.warn('warning: no nodes are enabled in fleet.yml')

// ---- compose services -------------------------------------------------------

const composeServices = {}
const composeVolumes = {}

for (const node of enabled) {
  const env = {
    BEE_API_ADDR: `:${node.apiPort}`,
    BEE_P2P_ADDR: `:${node.p2pPort}`,
    // Without an explicit NAT address, eight nodes behind one host advertise
    // unreachable addresses and inbound connectivity suffers.
    BEE_NAT_ADDR: `\${PUBLIC_IP}:${node.p2pPort}`,
    BEE_FULL_NODE: String(node.isFull),
    BEE_MAINNET: 'true',
    BEE_BLOCKCHAIN_RPC_ENDPOINT: '${GNOSIS_RPC_ENDPOINT}',
    BEE_PASSWORD: '${BEE_PASSWORD}',
    BEE_DATA_DIR: '/home/bee/.bee',
    BEE_CACHE_CAPACITY: String(node.cacheCapacity),
    BEE_VERBOSITY: node.verbosity,
    BEE_SWAP_ENABLE: 'true',
    BEE_STORAGE_INCENTIVES_ENABLE: String(node.incentives),
  }
  if (node.target_neighborhood) env.BEE_TARGET_NEIGHBORHOOD = String(node.target_neighborhood)
  if (node.isFull) env.BEE_RESERVE_CAPACITY_DOUBLING = String(node.doubling)

  composeServices[node.name] = {
    image: '${BEE_IMAGE}',
    container_name: `hawtch-${node.name}`,
    restart: 'unless-stopped',
    // The image is ENTRYPOINT ["bee"] with no CMD, so the subcommand must be
    // supplied. Without it the container runs `bee` bare, prints its help text
    // and exits — which looks like a crash loop with no useful error.
    command: ['start'],
    environment: env,
    volumes: [`${node.name}-data:/home/bee/.bee`],
    ports: [
      // API stays on loopback: bee's API is unauthenticated. Prometheus reaches
      // it over the docker network instead, so this mapping is admin-only.
      `127.0.0.1:${node.apiPort}:${node.apiPort}`,
      // P2P must be publicly reachable.
      `${node.p2pPort}:${node.p2pPort}`,
    ],
    networks: [fleet.network],
    labels: {
      'hawtch.role': node.role,
      'hawtch.node': node.name,
    },
  }
  // Declared external on purpose. These volumes hold funded wallets, and an
  // external volume is one compose is not allowed to create or destroy: `docker
  // compose down -v` skips it entirely. The explicit `name` also decouples the
  // volume from the compose project name, so a different -p can never silently
  // address a different (empty) volume.
  composeVolumes[`${node.name}-data`] = { external: true, name: `hawtch_${node.name}-data` }
}

write(
  'compose/docker-compose.bees.generated.yml',
  BANNER +
    yaml.dump(
      {
        services: composeServices,
        volumes: composeVolumes,
        networks: { [fleet.network]: { external: true } },
      },
      { lineWidth: 120, noRefs: true },
    ),
)

// ---- prometheus targets -----------------------------------------------------

write(
  'prometheus/targets/bee.generated.json',
  JSON.stringify(
    enabled.map((node) => ({
      targets: [`hawtch-${node.name}:${node.apiPort}`],
      labels: {
        node: node.name,
        role: node.role,
        node_type: node.isFull ? 'full' : 'light',
        neighborhood: String(node.target_neighborhood ?? ''),
      },
    })),
    null,
    2,
  ) + '\n',
)

// ---- reserve ceiling rules --------------------------------------------------

// The ceiling is not exposed as a metric (only via the status API), so it is
// injected here as a constant series per full node, joined on the `node` label.
const ceilingRules = enabled
  .filter((n) => n.isFull)
  .map((node) => ({
    record: 'hawtch:reserve_capacity_chunks',
    expr: String(node.reserveCapacity),
    labels: { node: node.name },
  }))

const reserveRules = {
  groups: [
    {
      name: 'hawtch-reserve',
      interval: '1m',
      rules: [
        ...ceilingRules,
        {
          record: 'hawtch:reserve_free_chunks',
          expr: 'hawtch:reserve_capacity_chunks - on(node) bee_localstore_reserve_size',
        },
        {
          record: 'hawtch:reserve_fill_chunks_per_second',
          // reserve_size is a gauge, so deriv() — not rate() — gives its slope.
          expr: 'deriv(bee_localstore_reserve_size[6h])',
        },
        {
          record: 'hawtch:reserve_seconds_to_full',
          // Only meaningful while the reserve is actually growing.
          expr:
            'hawtch:reserve_free_chunks / on(node) (hawtch:reserve_fill_chunks_per_second > 0)',
        },
      ],
    },
  ],
}

write('prometheus/rules/reserve.generated.yml', BANNER + yaml.dump(reserveRules, { lineWidth: 120 }))

// ---- sidecar probes ---------------------------------------------------------

// Each probe is defined by the pair of roles it measures across. Both halves must
// be enabled: pointing a probe's upload and download at the same node makes the
// download a local read, which measures nothing about the network. config.ts
// rejects that at runtime too, but failing here is cheaper than at deploy time.
const SIDECAR_SPECS = {
  latency: { uploadRole: 'data-upload', downloadRole: 'data-download', entrypoint: 'dist/latency.js' },
  beefeeder: { uploadRole: 'feed-upload', downloadRole: 'feed-download', entrypoint: 'dist/beefeeder.js' },
}

const sidecarConfig = fleet.sidecars ?? {}
const sidecarServices = {}
const sidecarTargets = []

for (const [name, spec] of Object.entries(SIDECAR_SPECS)) {
  const cfg = sidecarConfig[name]
  if (!cfg?.enabled) continue

  const uploader = enabled.find((n) => n.role === spec.uploadRole)
  const downloader = enabled.find((n) => n.role === spec.downloadRole)

  if (!uploader || !downloader) {
    const missing = [!uploader && spec.uploadRole, !downloader && spec.downloadRole].filter(Boolean)
    console.warn(
      `warning: sidecar "${name}" is enabled but no enabled node has role(s) ${missing.join(', ')} — skipping it. ` +
        `Enable the paired nodes in fleet.yml, or set sidecars.${name}.enabled to false.`,
    )
    continue
  }

  const metricsPort = cfg.metrics_port ?? (name === 'latency' ? 9101 : 9102)
  const env = {
    PROBE_NAME: name,
    // Container-to-container over the docker network: the API ports are bound to
    // loopback on the host and deliberately not reachable from outside.
    UPLOAD_BEE_URL: `http://hawtch-${uploader.name}:${uploader.apiPort}`,
    DOWNLOAD_BEE_URL: `http://hawtch-${downloader.name}:${downloader.apiPort}`,
    METRICS_PORT: String(metricsPort),
    INTERVAL_SECONDS: String(cfg.interval_seconds ?? 300),
    TIMEOUT_SECONDS: String(cfg.timeout_seconds ?? 120),
    POSTAGE_BATCH_ID: '${POSTAGE_BATCH_ID_' + name.toUpperCase() + ':-}',
    // Off unless explicitly enabled in .env: auto-buy on a restart loop spends
    // real xBZZ every time.
    POSTAGE_AUTO_BUY: '${POSTAGE_AUTO_BUY:-false}',
    POSTAGE_SIZE_GB: String(cfg.postage_size_gb ?? 1),
    POSTAGE_DURATION_DAYS: String(cfg.postage_duration_days ?? 30),
  }
  if (name === 'latency') env.PAYLOAD_BYTES = String(cfg.payload_bytes ?? 102400)
  if (name === 'beefeeder') {
    env.FEED_TOPIC = cfg.feed_topic ?? 'hawtch-hawtcher/beefeeder'
    // Must be stable across restarts: a new key is a new feed, and the reader
    // would then poll an address nobody writes to.
    env.FEED_PRIVATE_KEY = '${FEED_PRIVATE_KEY:?set FEED_PRIVATE_KEY in .env}'
  }

  sidecarServices[`sidecar-${name}`] = {
    build: { context: '../sidecars' },
    image: `hawtch/sidecar:${fleet.version ?? 1}`,
    container_name: `hawtch-sidecar-${name}`,
    restart: 'unless-stopped',
    command: ['node', spec.entrypoint],
    environment: env,
    depends_on: [uploader.name, downloader.name],
    networks: [fleet.network],
  }

  sidecarTargets.push({
    targets: [`hawtch-sidecar-${name}:${metricsPort}`],
    labels: {
      probe: name,
      uploader: uploader.name,
      downloader: downloader.name,
    },
  })
}

// Omit the `services` key entirely when no probe is wired: an empty mapping is
// not something compose should have to interpret, and this file is always passed
// with -f regardless.
write(
  'compose/docker-compose.sidecars.generated.yml',
  BANNER +
    yaml.dump(
      {
        ...(Object.keys(sidecarServices).length ? { services: sidecarServices } : {}),
        networks: { [fleet.network]: { external: true } },
      },
      { lineWidth: 120, noRefs: true },
    ),
)

write('prometheus/targets/sidecars.generated.json', JSON.stringify(sidecarTargets, null, 2) + '\n')

// ---- plain-text derivatives for the Makefile --------------------------------

// The Makefile used to shell out to node to read fleet.yml, which quietly made
// node a requirement on the deploy host. These two files keep it pure shell.
write('compose/enabled-nodes.generated.txt', enabled.map((n) => n.name).join(' ') + '\n')
write(
  'compose/ports.generated.txt',
  enabled.flatMap((n) => [`${n.name} api ${n.apiPort}`, `${n.name} p2p ${n.p2pPort}`]).join('\n') + '\n',
)
// Volume names the Makefile must create up front, since external volumes are
// never auto-created by compose.
write('compose/volumes.generated.txt', enabled.map((n) => `hawtch_${n.name}-data`).join(' ') + '\n')

// Everything tools/addresses.sh needs, so funding works on a host with no Node
// toolchain: name, role, api port, pinned neighborhood ("-" when unset).
write(
  'compose/nodes.generated.txt',
  enabled
    .map((n) => `${n.name} ${n.role} ${n.apiPort} ${n.target_neighborhood || '-'}`)
    .join('\n') + '\n',
)

// Fingerprint of the fleet.yml this output was rendered from.
//
// `make check-generated` compares content, not mtimes. Timestamps are useless
// for this: git sets them to checkout time in arbitrary order, so a fresh clone
// routinely leaves fleet.yml looking "newer" than files generated from it.
write(
  'compose/fleet.sha256.generated.txt',
  createHash('sha256').update(readFileSync(join(ROOT, 'fleet.yml'))).digest('hex') + '\n',
)

// ---- summary ----------------------------------------------------------------

console.log(`generated for ${enabled.length}/${nodes.length} enabled node(s):`)
for (const node of enabled) {
  const ceiling = node.reserveCapacity
    ? `, reserve ceiling ${node.reserveCapacity} chunks (~${Math.round((node.reserveCapacity * 4096) / 1024 ** 3)} GiB)`
    : ''
  console.log(`  ${node.name}  ${node.role}  api=${node.apiPort} p2p=${node.p2pPort}${ceiling}`)
}
const disabled = nodes.filter((n) => !n.enabled).map((n) => n.name)
if (disabled.length) console.log(`  (disabled: ${disabled.join(', ')})`)

function write(relPath, contents) {
  const abs = join(ROOT, relPath)
  mkdirSync(dirname(abs), { recursive: true })
  writeFileSync(abs, contents)
  console.log(`  wrote ${relPath}`)
}
